### ISSUE TITLE
Examples on how to use it.

### ISSUE THREAD

**Issue by aadrian** [takezoe/gitbucket-ci-plugin#70]
Please add some examples on how to use this plug-in.
(maybe configure one of the plug-ins or libraries to build with it?)

Thank you.

**Comment by berot3** [comment]
I use it for mkdocs, so I simply add this command to the Build script:
`python.exe -m mkdocs build`

(you might need the full path to python.exe)

**Comment by skullwritter** [comment]
@berot3 i have some questions for you, if you know how to respond of course
(this apply also to @takezoe, since we like this plugin, in  my case, i love, but too many empty spaces and i'll love to know how to use it totaly)

- wheres the documentation for this?
- how we create a release if the build it's successfull?
- if is available, how we set the assets?
- if it's available, how we specify what branches are elegible for releases?
- if it's available, how we set a file like travisCI?
- if is available, how we define an limit to releases and where to we specify an option in case that limit reaches?
- is there a option for generating the doc files like referred in #78
- is there a option for automatic builds then a certain time reaches?
- how is the #37 feature?
- is there an svg to show, like: "Build Status - Passing" instead of allways "unknown"?

this is the questions that i'll make for now, since we don't have a documentation for that.

**Comment by berot3** [comment]
I will try my best, but I am pretty much a started...

> 
> * wheres the documentation for this?

There is only the README afaik.

> * how we create a release if the build it's successfull?

I have no idea. Maybe as a git-command after the build?

> * if is available, how we set the assets?
> 
> * if it's available, how we specify what branches are elegible for releases?

Not sure what you mean. Have never done or needed this.

> * if it's available, how we set a file like travisCI?

I have to try travis, never used it.

> * if is available, how we define an limit to releases and where to we specify an option in case that limit reaches?
> 
> * is there a option for generating the doc files like referred in #78

No, don't think so. I would like to have something like gitlab is doing. But this is not possible atm (as far as I know)

> 
> * how is the #37 feature?

As you can see in the issue, I did not get a response yet.

> * is there an svg to show, like: "Build Status - Passing" instead of allways "unknown"?

Yes, when you have activated build it looks for example like this:  
`![badge](http://localhost:8080/mkdocs/test/build/master/badge.svg)`

> * for example, i would like to have, also an option for, when its android apps or core android to keep certain files to prevent bandwidth exaust

That would be another feature-request I guess.

> * option to download releases without login if repo is private?
> 

feature-request?

---

I am really new to gitbucket and yes, documentation could be better, at least for beginners. 

I use gitbucket because I want a small git-server on my PC. That I don't have all the features that the big server have makes only sense.

**Comment by thefiredragon** [comment]
A example would be great I create a repo with a sample maven Build and go to build Script with:

#!/bin/bash
/usr/bin/mvn clean package 

nothing is happen also under build i don‘t See a Button for run a build or can find any Logs what went wrong

**Comment by takezoe** [comment]
@thefiredragon Any script that works on the machine GitBucket is running should work and the build is triggered by pushing commits or tags (or comments which includes specific keywords).

**Comment by thefiredragon** [comment]
@takezoe 
perhaps something on my system went wrong.

Using debian 10 with openjdk11 
At your pictures I also see a build button which I don't see on my setup.
Docker is not required or? 
This VM is running internally

`2021-02-10 18:21:54.465:INFO::main: Logging initialized @151ms to org.eclipse.jetty.util.log.StdErrLog
2021-02-10 18:21:54.553:WARN:oejsh.ContextHandler:main: Empty contextPath
2021-02-10 18:21:54.558:INFO:oejs.Server:main: jetty-9.4.32.v20200930; built: 2020-09-30T16:16:37.804Z; git: de97d26f7bd222a0e16831e353d702a7a422f711; jvm 11.0.9.1+1-post-Debian-1deb10u2
2021-02-10 18:21:55.907:INFO:oejw.StandardDescriptorProcessor:main: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2021-02-10 18:21:56.151:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2021-02-10 18:21:56.151:INFO:oejs.session:main: No SessionScavenger set, using defaults
2021-02-10 18:21:56.153:INFO:oejs.session:main: node0 Scavenging every 600000ms
18:21:56.583 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
18:21:56.675 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
18:21:56.691 [main] WARN  slick.util.AsyncExecutor - Having maxConnection > maxThreads can result in deadlocks if transactions or database locks are used.
18:21:56.703 [main] INFO  g.core.servlet.InitializeListener - Check version
18:21:56.703 [main] INFO  g.core.servlet.InitializeListener - Start schema update
18:21:56.740 [main] INFO  g.core.servlet.InitializeListener - Extract bundled plugins...
18:21:56.759 [main] INFO  g.core.servlet.InitializeListener - Extract to /root/.gitbucket/plugins/gitbucket-notifications-plugin-1.10.0.jar
18:21:56.764 [main] INFO  g.core.servlet.InitializeListener - Extract to /root/.gitbucket/plugins/gitbucket-gist-plugin-4.20.0.jar
18:21:56.765 [main] INFO  g.core.servlet.InitializeListener - Extract to /root/.gitbucket/plugins/gitbucket-emoji-plugin-4.6.0.jar
18:21:56.779 [main] INFO  g.core.servlet.InitializeListener - Extract to /root/.gitbucket/plugins/gitbucket-pages-plugin-1.9.0.jar
18:21:56.780 [main] INFO  g.core.servlet.InitializeListener - Initialize plugins
18:21:56.864 [main] INFO  gitbucket.core.plugin.PluginRegistry - Initialize gitbucket-explorer-plugin-9.0.0.jar
18:21:57.085 [main] INFO  gitbucket.core.plugin.PluginRegistry - Initialize gitbucket-monitorting-plugin-5.0.0.jar
18:21:57.161 [main] INFO  gitbucket.core.plugin.PluginRegistry - Initialize gitbucket-commitgraphs-plugin_2.13-4.35.0.jar
18:21:57.177 [main] INFO  gitbucket.core.plugin.PluginRegistry - Initialize gitbucket-desktopnotify-plugin_2.13-4.32.0.jar
18:21:57.185 [main] ERROR gitbucket.core.plugin.PluginRegistry - Error during plugin initialization: gitbucket-desktopnotify-plugin_2.13-4.32.0.jar
java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at gitbucket.core.plugin.PluginRegistry$.$anonfun$initialize$3(PluginRegistry.scala:292)
	at gitbucket.core.plugin.PluginRegistry$.$anonfun$initialize$3$adapted(PluginRegistry.scala:284)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at gitbucket.core.plugin.PluginRegistry$.initialize(PluginRegistry.scala:284)
	at gitbucket.core.servlet.InitializeListener.$anonfun$contextInitialized$1(InitializeListener.scala:92)
	at gitbucket.core.servlet.InitializeListener.$anonfun$contextInitialized$1$adapted(InitializeListener.scala:60)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:207)
	at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:207)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:200)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:207)
	at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:60)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1068)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:561)
	at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:997)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:787)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:368)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1457)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1422)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:911)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:277)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:253)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:423)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:387)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at JettyLauncher.main(JettyLauncher.java:148)
Caused by: java.lang.AbstractMethodError: Receiver class me.huzi.gitbucket.desktopnotify.controller.DesktopNotifyController does not define or inherit an implementation of the resolved method 'abstract void gitbucket$core$service$ActivityService$_setter_$gitbucket$core$service$ActivityService$$formats_$eq(org.json4s.Formats)' of interface gitbucket.core.service.ActivityService.
	at gitbucket.core.service.ActivityService.$init$(ActivityService.scala:25)
	at me.huzi.gitbucket.desktopnotify.controller.DesktopNotifyController.<init>(DesktopNotifyController.scala:9)
	at Plugin.<init>(Plugin.scala:24)
	... 39 common frames omitted
18:21:57.186 [main] INFO  gitbucket.core.plugin.PluginRegistry - Initialize gitbucket-gist-plugin-4.20.0.jar
18:21:57.218 [main] INFO  gitbucket.core.plugin.PluginRegistry - Initialize gitbucket-emoji-plugin-4.6.0.jar
18:21:57.224 [main] INFO  gitbucket.core.plugin.PluginRegistry - Initialize gitbucket-label-kanban-plugin-3.7.0.jar
18:21:57.274 [main] INFO  gitbucket.core.plugin.PluginRegistry - Initialize gitbucket-application-logs-plugin-3.0.0.jar
18:21:57.286 [main] INFO  gitbucket.core.plugin.PluginRegistry - Initialize snakeyaml-1.25.jar
18:21:57.287 [main] ERROR gitbucket.core.plugin.PluginRegistry - Error during plugin initialization: snakeyaml-1.25.jar
java.lang.ClassNotFoundException: Plugin
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at gitbucket.core.plugin.PluginRegistry$.$anonfun$initialize$3(PluginRegistry.scala:292)
	at gitbucket.core.plugin.PluginRegistry$.$anonfun$initialize$3$adapted(PluginRegistry.scala:284)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at gitbucket.core.plugin.PluginRegistry$.initialize(PluginRegistry.scala:284)
	at gitbucket.core.servlet.InitializeListener.$anonfun$contextInitialized$1(InitializeListener.scala:92)
	at gitbucket.core.servlet.InitializeListener.$anonfun$contextInitialized$1$adapted(InitializeListener.scala:60)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:207)
	at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:207)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:200)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:207)
	at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:60)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1068)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:561)
	at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:997)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:787)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:368)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1457)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1422)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:911)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:277)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:253)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:423)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:387)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at JettyLauncher.main(JettyLauncher.java:148)
18:21:57.288 [main] INFO  gitbucket.core.plugin.PluginRegistry - Initialize gitbucket-ci-plugin-1.11.0.jar
18:21:57.615 [Thread-11] INFO  i.g.g.ci.manager.BuildJobThread - Start BuildJobThread-28
18:21:57.615 [Thread-10] INFO  i.g.g.ci.manager.BuildJobThread - Start BuildJobThread-27
18:21:57.627 [main] INFO  gitbucket.core.plugin.PluginRegistry - Initialize gitbucket-notifications-plugin-1.10.0.jar
18:21:57.645 [main] INFO  gitbucket.core.plugin.PluginRegistry - Initialize gitbucket-pages-plugin-1.9.0.jar
18:21:57.661 [main] INFO  gitbucket.core.plugin.PluginRegistry - Initialize gitbucket-mirror-plugin-1.3.0.jar
18:21:58.381 [main] INFO  l.servicelocator.ServiceLocator - Can not use class liquibase.parser.core.yaml.YamlChangeLogParser as a Liquibase service because org.yaml.snakeyaml.constructor.BaseConstructor is not in the classpath
18:21:58.382 [main] INFO  l.servicelocator.ServiceLocator - Can not use class liquibase.parser.core.json.JsonChangeLogParser as a Liquibase service because org.yaml.snakeyaml.constructor.BaseConstructor is not in the classpath
18:21:59.124 [main] ERROR gitbucket.core.plugin.PluginRegistry - Error during plugin initialization: gitbucket-mirror-plugin-1.3.0.jar
java.lang.NullPointerException: null
	at liquibase.sqlgenerator.core.RenameColumnGenerator.generateSql(RenameColumnGenerator.java:43)
	at liquibase.sqlgenerator.core.RenameColumnGenerator.generateSql(RenameColumnGenerator.java:15)
	at liquibase.sqlgenerator.SqlGeneratorChain.generateSql(SqlGeneratorChain.java:30)
	at liquibase.sqlgenerator.SqlGeneratorFactory.generateSql(SqlGeneratorFactory.java:223)
	at liquibase.sqlgenerator.SqlGeneratorFactory.generateSql(SqlGeneratorFactory.java:208)
	at io.github.gitbucket.solidbase.migration.LiquibaseMigration.migrate(LiquibaseMigration.java:91)
	at io.github.gitbucket.solidbase.migration.LiquibaseMigration.migrate(LiquibaseMigration.java:54)
	at io.github.gitbucket.solidbase.Solidbase.migrate(Solidbase.java:45)
	at io.github.gitbucket.solidbase.Solidbase.migrate(Solidbase.java:29)
	at gitbucket.core.plugin.PluginRegistry$.$anonfun$initialize$3(PluginRegistry.scala:309)
	at gitbucket.core.plugin.PluginRegistry$.$anonfun$initialize$3$adapted(PluginRegistry.scala:284)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at gitbucket.core.plugin.PluginRegistry$.initialize(PluginRegistry.scala:284)
	at gitbucket.core.servlet.InitializeListener.$anonfun$contextInitialized$1(InitializeListener.scala:92)
	at gitbucket.core.servlet.InitializeListener.$anonfun$contextInitialized$1$adapted(InitializeListener.scala:60)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:207)
	at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:207)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:200)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:207)
	at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:60)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1068)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:561)
	at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:997)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:787)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:368)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1457)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1422)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:911)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:277)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:253)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:423)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:387)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at JettyLauncher.main(JettyLauncher.java:148)
18:21:59.125 [main] INFO  gitbucket.core.plugin.PluginRegistry - Initialize gitbucket-rmarkdown-plugin_2.13-1.0.0.jar
18:21:59.146 [main] INFO  o.scalatra.servlet.ScalatraListener - The cycle class name from the config: ScalatraBootstrap
18:21:59.148 [main] INFO  o.scalatra.servlet.ScalatraListener - Initializing life cycle class: ScalatraBootstrap
18:21:59.152 [Thread-12] INFO  g.core.plugin.PluginWatchThread - Start PluginWatchThread: /root/.gitbucket/plugins
18:21:59.727 [main] INFO  o.a.s.c.u.s.b.BouncyCastleSecurityProviderRegistrar - getOrCreateProvider(BC) created instance of org.bouncycastle.jce.provider.BouncyCastleProvider
18:21:59.729 [main] INFO  o.a.s.c.u.s.e.EdDSASecurityProviderRegistrar - getOrCreateProvider(EdDSA) created instance of net.i2p.crypto.eddsa.EdDSASecurityProvider
18:21:59.806 [main] INFO  o.a.s.c.i.DefaultIoServiceFactoryFactory - No detected/configured IoServiceFactoryFactory using Nio2ServiceFactoryFactory
18:21:59.818 [main] INFO  gitbucket.core.ssh.SshServer$ - Start SSH Server Listen on 2222
2021-02-10 18:21:59.958:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@16ac4d3d{/,file:///root/.gitbucket/tmp/webapp/,AVAILABLE}{file:/opt/gitbucket/gitbucket.war}
2021-02-10 18:21:59.996:INFO:oejs.AbstractConnector:main: Started ServerConnector@299a06ac{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2021-02-10 18:21:59.997:INFO:oejs.Server:main: Started @5689ms
^C2021-02-10 18:23:18.821:INFO:oejs.AbstractConnector:JettyShutdownThread: Stopped ServerConnector@299a06ac{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2021-02-10 18:23:18.821:INFO:oejs.session:JettyShutdownThread: node0 Stopped scavenging
18:23:18.836 [JettyShutdownThread] INFO  gitbucket.core.ssh.SshServer$ - SSH Server is stopped.
18:23:18.836 [JettyShutdownThread] INFO  o.scalatra.servlet.ScalatraListener - Destroying life cycle class: ScalatraBootstrap
18:23:18.836 [JettyShutdownThread] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
18:23:18.844 [JettyShutdownThread] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
18:23:18.847 [Thread-12] INFO  g.core.plugin.PluginWatchThread - Shutdown PluginWatchThread
18:23:18.851 [Thread-10] INFO  i.g.g.ci.manager.BuildJobThread - Stop BuildJobThread-27
18:23:18.851 [Thread-11] INFO  i.g.g.ci.manager.BuildJobThread - Stop BuildJobThread-28
2021-02-10 18:23:18.905:INFO:oejsh.ContextHandler:JettyShutdownThread: Stopped o.e.j.w.WebAppContext@16ac4d3d{/,null,STOPPED}{file:/opt/gitbucket/gitbucket.war}`

**Comment by takezoe** [comment]
```
me.huzi.gitbucket.desktopnotify.controller.DesktopNotifyController does not define or inherit an implementation of the resolved method 'abstract void gitbucket$core$service$ActivityService$_set
```
gitbucket-desktopnotify-plugin doesn't seem to support a GitBucket version you use. Please remove it from your installation.
